// Code generated by MockGen. DO NOT EDIT.
// Source: logcat/logcat.go

// Package mock_logcat is a generated GoMock package.
package mock_logcat

import (
	gomock "github.com/golang/mock/gomock"
	devices "github.com/ybonjour/atr/devices"
	logcat "github.com/ybonjour/atr/logcat"
	test "github.com/ybonjour/atr/test"
	reflect "reflect"
)

// MockLogcat is a mock of Logcat interface
type MockLogcat struct {
	ctrl     *gomock.Controller
	recorder *MockLogcatMockRecorder
}

// MockLogcatMockRecorder is the mock recorder for MockLogcat
type MockLogcatMockRecorder struct {
	mock *MockLogcat
}

// NewMockLogcat creates a new mock instance
func NewMockLogcat(ctrl *gomock.Controller) *MockLogcat {
	mock := &MockLogcat{ctrl: ctrl}
	mock.recorder = &MockLogcatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLogcat) EXPECT() *MockLogcatMockRecorder {
	return m.recorder
}

// StartRecording mocks base method
func (m *MockLogcat) StartRecording(test test.Test) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartRecording", test)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartRecording indicates an expected call of StartRecording
func (mr *MockLogcatMockRecorder) StartRecording(test interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRecording", reflect.TypeOf((*MockLogcat)(nil).StartRecording), test)
}

// StopRecording mocks base method
func (m *MockLogcat) StopRecording(test test.Test) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopRecording", test)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopRecording indicates an expected call of StopRecording
func (mr *MockLogcatMockRecorder) StopRecording(test interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopRecording", reflect.TypeOf((*MockLogcat)(nil).StopRecording), test)
}

// MockFactory is a mock of Factory interface
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// ForDevice mocks base method
func (m *MockFactory) ForDevice(device devices.Device) logcat.Logcat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForDevice", device)
	ret0, _ := ret[0].(logcat.Logcat)
	return ret0
}

// ForDevice indicates an expected call of ForDevice
func (mr *MockFactoryMockRecorder) ForDevice(device interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForDevice", reflect.TypeOf((*MockFactory)(nil).ForDevice), device)
}
