// Code generated by MockGen. DO NOT EDIT.
// Source: test/installer.go

// Package mock_test is a generated GoMock package.
package mock_test_executor

import (
	apks "github.com/android-test-runner/atr/apks"
	devices "github.com/android-test-runner/atr/devices"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockInstaller is a mock of Installer interface
type MockInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockInstallerMockRecorder
}

// MockInstallerMockRecorder is the mock recorder for MockInstaller
type MockInstallerMockRecorder struct {
	mock *MockInstaller
}

// NewMockInstaller creates a new mock instance
func NewMockInstaller(ctrl *gomock.Controller) *MockInstaller {
	mock := &MockInstaller{ctrl: ctrl}
	mock.recorder = &MockInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInstaller) EXPECT() *MockInstallerMockRecorder {
	return m.recorder
}

// Reinstall mocks base method
func (m *MockInstaller) Reinstall(apk apks.Apk, device devices.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reinstall", apk, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reinstall indicates an expected call of Reinstall
func (mr *MockInstallerMockRecorder) Reinstall(apk, device interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reinstall", reflect.TypeOf((*MockInstaller)(nil).Reinstall), apk, device)
}
