// Code generated by MockGen. DO NOT EDIT.
// Source: junit_xml/formatter.go

// Package mock_junit_xml is a generated GoMock package.
package mock_junit_xml

import (
	gomock "github.com/golang/mock/gomock"
	apks "github.com/ybonjour/atr/apks"
	files "github.com/ybonjour/atr/files"
	result "github.com/ybonjour/atr/result"
	reflect "reflect"
)

// MockFormatter is a mock of Formatter interface
type MockFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockFormatterMockRecorder
}

// MockFormatterMockRecorder is the mock recorder for MockFormatter
type MockFormatterMockRecorder struct {
	mock *MockFormatter
}

// NewMockFormatter creates a new mock instance
func NewMockFormatter(ctrl *gomock.Controller) *MockFormatter {
	mock := &MockFormatter{ctrl: ctrl}
	mock.recorder = &MockFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFormatter) EXPECT() *MockFormatterMockRecorder {
	return m.recorder
}

// Format mocks base method
func (m *MockFormatter) Format(result []result.Result, apk apks.Apk) (files.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Format", result, apk)
	ret0, _ := ret[0].(files.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Format indicates an expected call of Format
func (mr *MockFormatterMockRecorder) Format(result, apk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Format", reflect.TypeOf((*MockFormatter)(nil).Format), result, apk)
}
